baseURL: "http://torbatti.ir/nim-cheat-sheet/"
enableInlineShortcodes: true
languageCode: "en-us"
title: "Nim Cheat Sheet"
theme: "uwe-uwe"
relativeURLs: true

disableKinds:
    - "section"
    - "taxonomy"
    - "term"
    - "RSS"

params:

    uweuwe:
        metadata:
            author: "Arya Bakhtiari"

        # logo: 
        #     display: true
        #     src: "/assets/img/uwe-uwe-logo.png"

        shortDesc: 
            display: true
            value: "Powered By Hugo And Uwe Uwe."

        platformLinks:
            display: true
            displayMode: "as-icons-and-text" # Possible values: as-text | as-icons | as-icons-and-text

            platforms:
                -   name: "github"
                    display: true
                    iconSrc: "/assets/img/icons-platforms/github-icon.svg"
                    target: "https://github.com/Torbatti/torbatti-site/nim-cheat-sheet"
                    text: "Github"
                    title: "Source Code For This Cheat Sheet"

        toc: 
            display: true

        renderHooks:
            image:
                use: true

            link:
                use: true

            heading:
                use: true

        syntaxHiglighingCustom:
            use: false

markup:
    goldmark:
        renderer:
            unsafe: true

    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: false
        hl_Lines: ""
        lineAnchors: ""
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        noClasses: true
        style: igor
        tabWidth: 4
